github: mozgbrasil
patreon: mozgbrasil
ko-fi: mozgbrasil
tidelift: mozgbrasil
open_collective: mozgbrasil
issuehunt: mozgbrasil
custom:
  - url: https://www.paypal.com/donate/?hosted_button_id=99SKT2QKZWZDA
